name: Build NG-GL4ES
on: [workflow_dispatch]
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Android NDK
        run: |
          echo "ANDROID_NDK_HOME=$HOME/android-ndk" >> $GITHUB_ENV
          wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
          unzip android-ndk-r25c-linux.zip -d $HOME >> /dev/null
      - name: Build Krypton Wrapper
        run: |
          mkdir -p build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake
          cmake --build .
      - name: Upload Krypton Wrapper libs
        uses: actions/upload-artifact@v3
        with:
          name: KryptonWrapper-android
          path: libs/*
      - name: Upload Krypton Wrapper debug libs
        uses: actions/upload-artifact@v3
        with:
          name: KryptonWrapper-android-debug
          path: 'obj/**/*.so'

  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build GL4ES
        run: |
          wget https://github.com/leetal/ios-cmake/raw/master/ios.toolchain.cmake
          cmake -B build -DCMAKE_TOOLCHAIN_FILE=ios.toolchain.cmake -DDEFAULT_ES=2 -DNOX11=ON -DNOEGL=OFF -DSTATICLIB=OFF -DPLATFORM=OS64 \
            -DCMAKE_C_FLAGS=-Wno-error=implicit-function-declaration
          cmake --build build --config RelWithDebInfo --target GL
      - name: Upload lib
        uses: actions/upload-artifact@v3
        with:
          name: gl4es-114-ios
          path: lib/Release
